services:
        eomt:
          build:
            context: ./
            args:
              USER_ID: ${USERID}
              GROUP_ID: ${GROUPID}
              USER_NAME: ${USERNAME}
          image: "pdh_eomt"
          container_name: ${CONTAINERNAME} 
          network_mode: "host"
          volumes:
            - "/home/${USERNAME}/workspace:/home/${USERNAME}/workspace"
            - "/dev/:/dev/"
            - "/tmp/.X11-unix:/tmp/.X11-unix"
            - "/dev/snd:/dev/snd"
            - "$HOME/.Xauthority:/$HOME/.Xauthority:rw"
            - "/dataset:/dataset"
            - "/data:/data"
            - "/home/${USERNAME}/.ssh/:/home/${USERNAME}/.ssh/"
            - "/home/${USERNAME}/.cache/huggingface/:/home/${USERNAME}/.cache/huggingface"
            - "/home/${USERNAME}/.cache/:/home/${USERNAME}/.cache/"
          environment:
            - "DISPLAY"
          device_cgroup_rules:
            - "c 81:* rmw"
            - "c 189:* rmw"
          deploy:
            resources:
              reservations:
                devices:
                    - driver: nvidia 
                      capabilities: [gpu]
                      count: -1
          stdin_open: true
          tty: true
